export const UPDATE_POST_LIKES = "UPDATE_POST_LIKES";
export const UPDATE_POST_REPLY_LIKES = "UPDATE_POST_REPLY_LIKES";
export const UPDATE_POSTS_SUBREPLY_LIKES = "UPDATE_POSTS_SUBREPLY_LIKES";

export const ADD_POST_COMMENT = "ADD_POST_COMMENT";
export const ADD_POST_SUB_COMMENT = "ADD_POST_SUB_COMMENT";