export const UPDATE_POST = "UPDATE_POST";
export const UPDATE_POST_LIKES = "UPDATE_POST_LIKES";
export const UPDATE_POST_REPLY_LIKES = "UPDATE_POST_REPLY_LIKES";

export const ADD_POST_COMMENT = "ADD_POST_COMMENT";